### PR TITLE
Changed it to 1 day

### PR DESCRIPTION
**Pull request by bovard**
#### The problem
I want to go to lunch sometimes every 12 days sometimes every 13 days. BUT I CAN'T

#### The solution
Change the threshold to 1 day

#### To test
1. eat lunch on Monday
2. eat lunch on Wednesday

@dominicfrost

### CODE REVIEW

**Comment by nathanevans-wf** [comment]
+1

**Comment by jonmccracken-wf** [comment]
+1

**Comment by mackenzieobleness-wf** [comment]
+1

**Comment by davidmarne-wf** [comment]
+1

**Comment by dominicfrost** [comment]
I can't merge without unit tests.

**Comment by jonmccracken-wf** [comment]
man

**Pull request merged**
